#!/usr/bin/env python3
"""
ReconMaster Alert Manager
Sends notifications for detected changes
"""

import os
import json
import smtplib
import requests
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, List


class AlertManager:
    """Manages alerts and notifications"""
    
    def __init__(self, config: Dict):
        self.config = config
        self.enabled = config.get("enabled", True)
    
    def send_alerts(self, target: str, changes: List[Dict], scan_dir: str):
        """Send alerts for detected changes"""
        if not self.enabled or not changes:
            return
        
        print(f"\n[+] Sending alerts for {len(changes)} changes...")
        
        # Prepare alert message
        message = self._format_alert_message(target, changes, scan_dir)
        
        # Send via configured channels
        if self.config.get("email", {}).get("enabled", False):
            self._send_email_alert(target, message)
        
        if self.config.get("slack", {}).get("enabled", False):
            self._send_slack_alert(target, message)
        
        if self.config.get("discord", {}).get("enabled", False):
            self._send_discord_alert(target, message)
        
        # Always save to file
        self._save_alert_to_file(target, message, scan_dir)
    
    def _format_alert_message(self, target: str, changes: List[Dict], scan_dir: str) -> str:
        """Format alert message"""
        lines = []
        lines.append(f"🔍 ReconMaster Alert - {target}")
        lines.append(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"Scan Directory: {scan_dir}")
        lines.append("")
        lines.append(f"📊 Total Changes Detected: {len(changes)}")
        lines.append("")
        
        # Group by severity
        critical = [c for c in changes if c.get("severity") == "critical"]
        high = [c for c in changes if c.get("severity") == "high"]
        medium = [c for c in changes if c.get("severity") == "medium"]
        low = [c for c in changes if c.get("severity") == "low"]
        
        if critical:
            lines.append("🚨 CRITICAL CHANGES:")
            for change in critical:
                lines.append(f"  • {change['description']}")
                if isinstance(change.get("details"), list):
                    for detail in change["details"][:5]:  # Limit to 5 items
                        lines.append(f"    - {detail}")
            lines.append("")
        
        if high:
            lines.append("⚠️ HIGH PRIORITY:")
            for change in high:
                lines.append(f"  • {change['description']}")
            lines.append("")
        
        if medium:
            lines.append("📊 MEDIUM PRIORITY:")
            for change in medium:
                lines.append(f"  • {change['description']}")
            lines.append("")
        
        if low:
            lines.append("ℹ️ LOW PRIORITY:")
            for change in low:
                lines.append(f"  • {change['description']}")
            lines.append("")
        
        lines.append("---")
        lines.append("Generated by ReconMaster Monitoring System")
        
        return "\n".join(lines)
    
    def _send_email_alert(self, target: str, message: str):
        """Send email alert"""
        try:
            email_config = self.config.get("email", {})
            
            # Email configuration
            smtp_server = email_config.get("smtp_server", "smtp.gmail.com")
            smtp_port = email_config.get("smtp_port", 587)
            sender_email = email_config.get("sender_email")
            sender_password = email_config.get("sender_password")
            recipient_emails = email_config.get("recipient_emails", [])
            
            if not sender_email or not sender_password or not recipient_emails:
                print("[!] Email configuration incomplete")
                return
            
            # Create message
            msg = MIMEMultipart()
            msg["From"] = sender_email
            msg["To"] = ", ".join(recipient_emails)
            msg["Subject"] = f"🔍 ReconMaster Alert - {target}"
            
            msg.attach(MIMEText(message, "plain"))
            
            # Send email
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(sender_email, sender_password)
                server.send_message(msg)
            
            print(f"[+] Email alert sent to {len(recipient_emails)} recipient(s)")
            
        except Exception as e:
            print(f"[!] Error sending email alert: {e}")
    
    def _send_slack_alert(self, target: str, message: str):
        """Send Slack alert"""
        try:
            slack_config = self.config.get("slack", {})
            webhook_url = slack_config.get("webhook_url")
            
            if not webhook_url:
                print("[!] Slack webhook URL not configured")
                return
            
            # Format for Slack
            payload = {
                "text": f"🔍 *ReconMaster Alert - {target}*",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": message.replace("🚨", ":rotating_light:").replace("⚠️", ":warning:").replace("📊", ":bar_chart:")
                        }
                    }
                ]
            }
            
            response = requests.post(webhook_url, json=payload)
            
            if response.status_code == 200:
                print("[+] Slack alert sent successfully")
            else:
                print(f"[!] Slack alert failed: {response.status_code}")
                
        except Exception as e:
            print(f"[!] Error sending Slack alert: {e}")
    
    def _send_discord_alert(self, target: str, message: str):
        """Send Discord alert"""
        try:
            discord_config = self.config.get("discord", {})
            webhook_url = discord_config.get("webhook_url")
            
            if not webhook_url:
                print("[!] Discord webhook URL not configured")
                return
            
            # Discord has a 2000 character limit
            if len(message) > 1900:
                message = message[:1900] + "\n... (truncated)"
            
            payload = {
                "content": f"```\n{message}\n```"
            }
            
            response = requests.post(webhook_url, json=payload)
            
            if response.status_code == 204:
                print("[+] Discord alert sent successfully")
            else:
                print(f"[!] Discord alert failed: {response.status_code}")
                
        except Exception as e:
            print(f"[!] Error sending Discord alert: {e}")
    
    def _save_alert_to_file(self, target: str, message: str, scan_dir: str):
        """Save alert to file"""
        try:
            alert_file = os.path.join(scan_dir, "ALERT.txt")
            with open(alert_file, 'w') as f:
                f.write(message)
            print(f"[+] Alert saved to: {alert_file}")
        except Exception as e:
            print(f"[!] Error saving alert to file: {e}")
    
    def test_alerts(self):
        """Test alert configuration"""
        print("\n[*] Testing alert configuration...")
        
        test_changes = [
            {
                "type": "test",
                "severity": "critical",
                "description": "This is a test alert from ReconMaster",
                "details": ["Test detail 1", "Test detail 2"]
            }
        ]
        
        self.send_alerts("test.example.com", test_changes, "/tmp/test_scan")
        print("[+] Test complete")


def main():
    """Test the alert manager"""
    import yaml
    
    # Load config
    config_file = "config/monitoring_config.yaml"
    if os.path.exists(config_file):
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)
    else:
        config = {"alerting": {"enabled": True}}
    
    alert_manager = AlertManager(config.get("alerting", {}))
    alert_manager.test_alerts()


if __name__ == "__main__":
    main()
